[package]
name = "config_info_derive"
version = "0.1.0"
edition = "2018"
publish = false

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1"
quote = "1"
serde = "1.0"
syn = { version = "1", features = ["extra-traits", "full"] }
