[package]
name = "config_info"
version = "0.1.0"
edition = "2018"
publish = false

[dependencies]
config_info_derive = { path = "./config_info_derive" }
serde = { version = "1.0", features = ["derive"] }

[dev-dependencies]
serde_derive = "1.0"
serde_json = "1.0"
tikv_util = { path = "../tikv_util" }
toml = "0.5"
